"""empty message

Revision ID: 51465c259766
Revises: d3947f4819e9
Create Date: 2020-12-16 07:16:02.086924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51465c259766'
down_revision = 'd3947f4819e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
